[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/erikngigi"

[social.params]
icon = "tabler/brand-github"
newTab = true

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://linkedin.com/in/erikngigi"

[social.params]
icon = "tabler/brand-linkedin"
newTab = true

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://youtube.com/@erikngigi"

[social.params]
icon = "tabler/brand-youtube"
newTab = true

[[social]]
identifier = "upwork"
name = "Upwork"
url = "https://www.upwork.com/freelancers/~0158c05089674278af?viewMode=1"

[social.params]
icon = "tabler/brand-upwork"
newTab = true

# [[main]]
# identifier =
# name = 
# url = 
# weight =
#
# [[main.params]]
# icon = 
# newTab =
